### PR TITLE
fix: tolerate IPv6 being unavailable on the host

### LINKED ISSUE #17: Fails to start when IPv6 is disabled
We need to gracefully allow the IPv6 socket to fail to start which happens on a host that has it disabled system-wide.

### PR DESCRIPTION
**Pull request by pdugas**
Fixes #17

The sender now gracefully handles systems where IPv6 is unavailable or disabled. Previously, NewUDPSender() would fail completely if IPv6 socket creation failed, preventing the application from starting even for IPv4-only workloads.

Changes:
- Modified NewUDPSender() to make IPv6 socket creation optional
- Added check in Send() to return clear error when IPv6 packets are requested but IPv6 is unavailable
- Updated tests to handle optional IPv6 support
- Updated documentation to reflect IPv6 as optional feature

The sender now operates in IPv4-only mode when IPv6 is unavailable while maintaining full functionality when both protocols are supported.

### CODE REVIEW

File: sender.go [hunk 1]
```diff
@@ -54,17 +54,16 @@ func NewUDPSender(maxPayloadIPv4, maxPayloadIPv6 int) (*UDPSender, error) {
...
 	sender.fdIPv4 = fd4
 
-	// Create IPv6 socket
+	// Create IPv6 socket (optional - failure is tolerated)
 	fd6, err := syscall.Socket(syscall.AF_INET6, syscall.SOCK_RAW, syscall.IPPROTO_RAW)
 	if err != nil {
-		// Clean up IPv4 socket
-		_ = syscall.Close(sender.fdIPv4)
-		return nil, fmt.Errorf("failed to create raw IPv6 socket (requires root): %w", err)
+		// IPv6 not available - this is acceptable, just log and continue with IPv4 only
```
Comment (fbonecco-cribl) [inline sender.go]: ```just log and continue```  are we logging actually?

File: sender.go [hunk 2]
```diff
@@ -122,6 +121,11 @@ func (s *UDPSender) Send(message string, srcIP net.IP, srcPort uint16, destIP ne
 
 	// Check if both are IPv6
 	if !isSrcIPv4 && !isDestIPv4 {
+		// Check if IPv6 is available
```
Comment (fbonecco-cribl) [inline sender.go]: It might make sense for this validation to take precedence over actual payload-size checks. This would be merely to avoid confusing users; if IPv6 is disabled but still attempted using an offending payload (one that's larger than allowed), users will see ```payload size X exceeds MTU limit for A (B bytes)``` first, rather than ```IPv6 is not available on this system```

**Review by fbonecco-cribl — DISMISSED** [review]
@pdugas - LGTM. Added 2 minor comments that, if addressed, would help during troubleshooting.

**Comment by awhittier-cribl** [comment]
Tests pass locally and the changes look reasonable to me (I don't know Go so take that for what it's worth ¯\_(ツ)_/¯).

**Review by awhittier-cribl — APPROVED** [review]

**Review by fbonecco-cribl — APPROVED** [review]
